GET http://localhost:3000/subscribers/
###
GET http://localhost:3000/subscribers/60dd7951bb7daa38b4efd8b4
###
POST http://localhost:3000/subscribers
Content-Type: application/json

{ 
    "name": "Binh",
    "subscriberToChannel": "BinhChannel"
}
### 
PATCH http://localhost:3000/subscribers/60dd826a391b83054cf411ea
CONTENT-TYPE: application/json

{
    "name": "Quynh Anh",
    "subscriberToChannel": "Binh 's heart"
}
###
DELETE http://localhost:3000/subscribers/60dd7951bb7daa38b4efd8b4